version: '3.4'
services:
  api:
    image: channelcat/docasaurus
    ports:
     - 80
    environment:
      - GIT_HOST
      - GIT_COMMITTER_NAME
      - GIT_COMMITTER_EMAIL
      - GIT_USERNAME
      - GIT_PASSWORD
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
      - APP_URL
  redis:
    image: redis
